In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [3]:
from google.colab import files
uploaded = files.upload()

Saving archive (1).zip to archive (1).zip

In [4]:
import zipfile

with zipfile.ZipFile('archive (1).zip', 'r') as zip_ref:
    zip_ref.extractall('dataset')

In [5]:
import os

os.listdir('dataset')

['spam.csv']

In [6]:
import os

for root, dirs, files in os.walk('dataset'):
    for file in files:
        print(os.path.join(root, file))

dataset/spam.csv

In [7]:
df = pd.read_csv("dataset/spam.csv", encoding='latin-1')

df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [9]:
print(df.columns)

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [10]:
print(df.shape)

(5572, 5)

In [11]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [12]:
print(df.columns.tolist())

['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [13]:
df = df.loc[:, ~df.columns.str.contains('Unnamed')]

In [14]:
df.columns = ['label', 'message']

In [15]:
print(df.columns)

Index(['label', 'message'], dtype='object')

In [16]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [17]:
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

In [18]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    return text

df['message'] = df['message'].apply(clean_text)

In [33]:
def predict_spam(message):

    message_tfidf = vectorizer.transform([message])

    prediction = model.predict(message_tfidf)

    return prediction[0]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [25]:
y_pred = model.predict(X_test)

In [26]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [27]:
predictions = model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, predictions))

Accuracy: 0.9551569506726457

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       965
           1       0.99      0.67      0.80       150

    accuracy                           0.96      1115
   macro avg       0.97      0.84      0.89      1115
weighted avg       0.96      0.96      0.95      1115

In [37]:
def predict_spam(message):

    message_tfidf = vectorizer.transform([message])  # or tfidf if that's your variable name

    prediction = model.predict(message_tfidf)

    if prediction[0] == 1:
        return "Spam"
    else:
        return "Not Spam"

In [39]:
msg = "Hi, are we meeting tomorrow?"
print(predict_spam(msg))

Not Spam

In [40]:
msg = "Congratulations! You have won a free iPhone. Claim your prize now."

print(predict_spam(msg))

Spam